### ISSUE TITLE
Tech term definitions?

### ISSUE THREAD

**Issue by jackfirth** [florence/reactor#1]
I'm having some trouble navigating the docs, and I think it would help a lot if some `@deftech{}`s were sprinkled about and linked to. Here's some I'd personally find helpful:

- process
- reactor
- signal
- current process
- paused process
- independent process
- prime a process
- reaction
- instantaneous
- this instant
- pause
- block
- emit

**Comment by florence** [comment]
It would probably help if all of these were actually defined in the documentation too...

(tho some of these, like `prime` and `emit are probably missing an `@racket` rather than an `@tech`.

**Comment by florence** [comment]
Also seems the documentation is rather out of date...

**Comment by florence** [comment]
(I dont mean to be glib, thank you for pointing this out! Should have the docs rewrite done tomorrow)

**Comment by jackfirth** [comment]
FYI this is not a pressing issue for me in any way, so don't worry if you don't get it done tomorrow.

**Comment by florence** [comment]
Some new docs pushed!
