### ISSUE TITLE
Non-macro API?

### ISSUE THREAD

**Issue by jackfirth** [florence/reactor#2]
The `define-process` form is great and very user friendly. But for abstractions built on top of reactor, or for compatibility layers between it and other concurrency libraries, I'd like constructor functions like `make-process`, `make-reactor`, and `make-signal` that expose the reaction state machine explicitly. It would also help people refine their mental model of what these things do. What do you think?

**Comment by florence** [comment]
`make-process` exists and is called `process`. It must be a syntactic form because most reactive forms (like `par&`) can only exist within a syntactically within `process` or `define-process`.

`make-reactor` exists and is called `prime`. Tis a silly name, and I could be convinced to change it.

`make-signal` could exist, but I don't see it being useful, since signals are given a name anyways. It would also probably need to be a form rather than a function to support multi-valued signals in a non-ugly way?

>"Expose the reaction state machine directly"

I don't understand this comment.

**Comment by jackfirth** [comment]
What I mean is, you can desugar from the macros to a state machine that has no blocking at all and has regular Racket evaluation semantics. This works by turning processes into functions that return either the final result of a process, or a continuation-like value that indicates to the reactor running the process what the process wants to do next. Imagine a `make-process` function like this:

> ```
> (make-process [proc (-> (or/c process-result? process-step?)])
>   -> process?
> ```
> 
> Constructs a process that calls `proc` when started, expecting it to return instantaneously. Non-instantaneous computation is expressed by `proc` returning a _step_, which describes some asynchronous behavior the process needs to perform such as spawning a new process, blocking on another process, reading or emitting a signal, or suspending. Steps include a procedure to call with whatever values the process step demanded (such as signal emissions and process results); that procedure is similar to `proc` and returns either a process result or the next step. Running a process implies recursively handling these steps to eventually obtain a process result.
>
> When a process is part of a reactor, the reactor calls `proc` and performs the asynchronous actions requested by each step. Note that some steps (such as spawning new processes and reading signals) do not pause a process and can be handled instantaneously by a reactor, so steps are not one-to-one with instants. A single instant in a reactor may be the result of many steps across multiple processes. A reactor only stops the current instant once every process within the reactor returns a step that cannot be handled instantaneously.

This is very similar in spirit to function trampolining. Think of it as a low level interface that `process` could expand to. Now I can write reactors myself, and - presuming a similar reactor constructor like `make-reactor` - I can add debugging and introspection wrappers around reactors. Most users shouldn't need to do this, but it makes it easier to write useful libraries on top of `reactor` for those users. For instance, I could write a reactor that schedule process execution across a pool of worker places.

**Comment by florence** [comment]
> What I mean is, you can desugar from the macros to a state machine that has no blocking at all and has regular Racket evaluation semantics.

I'm not sure that this makes sense, for several reasons:

1. The removes the goal of determinism. While each reaction is deterministic, the individual steps are not. Depending on the scheduler the number of steps may change. And, if a uses use racket level side effects but is careful to maintain overall determinism, this could break that too, as intermediate steps are expose to the outside world.

2. This breaks the abstractions of the system. The forms of this language provide a good abstraction for the kinds of control flow they are meant to describe. (I claim this based of my experience with Esterel and ReactiveML, and the careful design that has gone into these languages).

3. Reactor's compiler is not syntactic sugar. Or, put another way, This is truly a language in that there are some things the system doesn't let you say at all. I don't see a way to do this without loosing the guarantees that the system needs to operate.  Look at, for example, the compilation of the simple case of abort: (https://github.com/florence/reactor/blob/master/compiler.rkt#L123). Exactly where continuations are captured, and how the extensions to continuations that reactor uses are setup is subtle, and it breaks very easily if they aren't set up just right. This, fundamentally, is why there is a section of the docs that describes how certain kinds of control jumps are undefined behavior. (And I do truly mean *undefined* here. I make no guarantees).
 

Also a couple of comments on what you propose: 

>which describes some asynchronous behavior the process needs to perform such as spawning a new process
The goal here is to *not* have asynchronous computation within the system. A reaction is a fully synchronous process.  Asynchronous behavior should occur outside of a reactor. (or maybe in the task system I hope to get working some day).

Also the terminology of "process spawning" in the current docs is just plain wrong. Also the term `process` is misleading, but I don't have a better one right now. (Reactive Function might be better but that just sounds bleh).

>This is very similar in spirit to function trampolining.

the runtime of the system does a trampolining process like this. You do *not* want to implement this. Its a mess. And if I gave you that abilility you would essentually just be reimplementing the runtime.

> Now I can write reactors myself

Now I'm thinking that the documentation on what a reactor is isn't clear. A `reactor` is just an encapsulation of the state of a running reactive program. You can make your own (in so much as there contents is just the current running state of whatever reactive process there were primed with, and those are something you write).

> I can add debugging and introspection wrappers around reactors.

You can already do this. Process are formed of reactive code *and* normal racket code. The reason `reactor-continuation-marks` exists is to facilitate things like debuggers and steppers. (One of these I am currently working on for reactor). 

also oh look the documentation for `reactor-continuation-marks` is also out of date... You can see some meh examples here: https://github.com/florence/reactor/blob/master/tests/marks.rkt
